=> Saving data in Logs/FRL~try=4
dataset to use is:  CIFAR10
number of FL clients:  1000
non-iid degree data distribution:  1.0
batch size is :  8
test batch size is:  128
Files already downloaded and verified
Files already downloaded and verified
use_cuda:  True
type of FL:  My_attack
#########Federated Learning using Rankings############
fraction of maliciou clients: 0.10 | total number of malicious clients: 100
Traceback (most recent call last):
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/test/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/test/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/test/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/test/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/test/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/test/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/test/FRL/main.py", line 115, in <module>
    main()
  File "/home/test/FRL/main.py", line 100, in main
    My_attack(tr_loaders, te_loader)
  File "/home/test/FRL/FL_train.py", line 88, in My_attack
    final,p = optimizer.optimize_p()
  File "/home/test/FRL/loss_new.py", line 171, in optimize_p
    loss = -α*cos_sim+(1-α)*cos_sim_mid
NameError: name 'α' is not defined